---
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: Platform_Service
  description: plat auth
  tags:
    - jenkins
    - jira 
    - postman
  system:
    - ocs
#   annotations:
#     backstage.io/techdocs-ref: "https://documenter.getpostman.com/view/15548094/"
    
#     environment: "production"
  links:
    - url: https://goyubi.atlassian.net/jira/software/c/projects/CP/boards/53?quickFilter=186
      title: Jira Dashboard
      icon: dashboard
      type: jira-dashboard
    - url: https://jenkins.dso.credavenue.io/job/Platforms/job/UserAuth/job/Api/job/Prd/
      title: Jenkins Dashboard
      icon: dashboard
      type: jenkins-dashboard
    - url: https://documenter.getpostman.com/view/15548094/TzXwFe7Q
      title: APIs/Swagger link
      icon: dashboard
      type: postman-dashboard
    - url: https://documenter.getpostman.com/view/15548094/TzY7dtsP
      title: User Service Apis
      icon: dashboard
      type: postman-dashboard
    - url: https://documenter.getpostman.com/view/15548094/2s847PKA4L
      title: CNS
      icon: dashboard
      type: postman-dashboard
spec:
  type: service
  lifecycle: production
  owner: platform-team
  system: platform
        
  consumesApis: 
    - Auth0_Services
    - CNS_services
  dependencyOf: 
    - component:Credit
    - component:Pools
    - component:Co-lending
    - component:SCF
    - component:Loans
    - component:Invest
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: Auth0_Services
spec:
  type: openapi
  lifecycle: production
  owner: thirdparty
---
apiVersion: backstage.io/v1alpha1
kind: API
metadata:
  name: CNS_services
spec:
  type: openapi
  lifecycle: production
  owner: thirdparty
---
  
